### ISSUE TITLE
Static assert failure when compiling procyon as part of antares

### ISSUE THREAD

**Issue by mlindner** [arescentral/procyon#1]
clang++ -mmacosx-version-min=10.7 -MMD -MF obj/ext/procyon/src/cpp/src/libprocyon-cpp.value.o.d -DNDEBUG -I../../../ext/procyon/src/cpp/include -I../../../ext/procyon/src/c/include -Os -Wall -Wextra -Wsign-compare -Werror -Wno-initializer-overrides -std=c++11 -stdlib=libc++ -c ../../../ext/procyon/src/cpp/src/value.cpp -o obj/ext/procyon/src/cpp/src/libprocyon-cpp.value.o
../../../ext/procyon/src/cpp/src/value.cpp:158:1: error: static_assert failed "allows char conversion"
static_assert(conversion<value, char>::fails, "allows char conversion");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../ext/procyon/src/cpp/src/value.cpp:159:1: error: static_assert failed "allows signed char conversion"
static_assert(conversion<value, signed char>::fails, "allows signed char conversion");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../ext/procyon/src/cpp/src/value.cpp:160:1: error: static_assert failed "allows unsigned char conversion"
static_assert(conversion<value, unsigned char>::fails, "allows unsigned char conversion");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../ext/procyon/src/cpp/src/value.cpp:163:1: error: static_assert failed "allows void* conversion"
static_assert(conversion<value, void*>::fails, "allows void* conversion");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../ext/procyon/src/cpp/src/value.cpp:164:1: error: static_assert failed "allows char* conversion"
static_assert(conversion<value, char*>::fails, "allows char* conversion");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 errors generated.

**Comment by sfiera** [comment]
What’s `clang --version` and `xcodebuild -version` for you? These checks aren’t strictly necessary but it would be nice to leave the safeties on.

**Comment by mlindner** [comment]
mlindner$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

mlindner$ xcodebuild -version
Xcode 7.2.1
Build version 7C1002

**Comment by sfiera** [comment]
I added Xcode 7.3 to the Travis configuration for the repo, but Travis doesn’t have a 7.2 image available, so I have no way to test this or prevent regressions.

If this isn’t fixed, can you provide `__apple_build_version__` for your clang?

    $ clang -dM -E - </dev/null |grep __apple_build_version__
